FROM fedora:36

ENV PLATFORM=web

ENV EMSCRIPTEN_VERSION=3.1.18

RUN dnf -y install --setopt=install_weak_deps=False \
    bash bzip2 curl file findutils git make nano patch pkgconfig python3-pip unzip which xz

RUN pip install scons==4.4.0

RUN git clone --branch ${EMSCRIPTEN_VERSION} --progress https://github.com/emscripten-core/emsdk && \
    emsdk/emsdk install ${EMSCRIPTEN_VERSION} && \
    emsdk/emsdk activate ${EMSCRIPTEN_VERSION} && echo 'source "/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
CMD /bin/bash

COPY .github/docker/build.sh /build.sh

ENTRYPOINT ["/build.sh"]
