name: CI
on:
  workflow_dispatch:
    inputs:
      profile:
        description: ENV Profile
        default: DEFAULT
        required: true

env:
  SECRET_KEY: ${{ secrets[format('{0}_KEY', github.event.inputs.profile)] }}

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        name: ["linuxbsd"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and extract Godot
        shell: bash
        run: |
          curl -fLO https://github.com/godotengine/godot/archive/refs/heads/4.0.zip
          unzip -q 4.0.zip -x ".github/*"
          ls -la

      - name: Setup build cache
        env:
          CACHE_NAME: sconscache
        uses: actions/cache@v3
        with:
          path: .scons-cache/
          key: sconscache-${{matrix.name}}
          restore-keys: sconscache-${{matrix.name}}

      - name: Build Docker Image
        run: |
          chmod 744 .github/docker/build.sh
          docker build -t container -f ./.github/docker/Dockerfile.${{matrix.name}} .
      
      - name: Setup Build Profiles
        continue-on-error: true
        run: |
          echo "${{ vars[format('{0}_PROFILE', github.event.inputs.profile)] }}" >> custom.py
          echo "${{ vars[format('{0}_FEATURE_PROFILE', github.event.inputs.profile)] }}" >> feature_profile.build

      - name: Run Docker Image
        run: docker run -v "${{github.workspace}}":"/github/workspace" container ${{matrix.name}} ${{env.SECRET_KEY}} 

      - name: Prepare Artifact
        continue-on-error: true
        run: |
          ls -la bin
          ls -la 

      - name: Upload Artifact
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: templates
          path: bin/*
          retention-days: 3
