name: 🛠️ Godot Build Service
on: 
    workflow_dispatch:

env:
    version: "4.0.1"
    
jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Download and extract Godot
            run: |
                mkdir -p source
                wget -q -O godot.tar.gz https://github.com/godotengine/godot/archive/refs/tags/${{env.version}}-stable.tar.gz
                tar xf godot.tar.gz --directory source/ --strip-components=1 --exclude=".*"
                rm -rf godot.tar.gz && rm -rf source/editor
                ls -la
                ls -la source
  
  
