name: Test
on:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Download and extract Godot
            shell: bash
            run: |
                pwd
                ls -la
                wget -q -O godot.tar.gz https://github.com/godotengine/godot/archive/refs/tags/4.0.1-stable.tar.gz
                tar xf godot.tar.gz --strip-components=1
                ls -la
  
  
