name: 🛠️ Godot Build Service
on: 
  workflow_dispatch:

env:
  version: "4.0.1"
  SECRET_KEY: ${{ secrets[format('{0}_KEY', github.event.inputs.profile)] }}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: godot
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        name: ["windows", "linuxbsd", "web", "android"]
        arch: ["x86_64", "i686"]
        exclude:
          - name: web
            arch: "i686"
          - name: android
            arch: "i686"
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Prepare Enviroment
      run: |
        mkdir source templates .scons-cache .docker-cache
        wget -q -O godot.tar.gz https://github.com/godotengine/godot/archive/refs/tags/${{env.version}}-stable.tar.gz
        tar xf godot.tar.gz --directory source --strip-components=1 --exclude=".*"
        rm -rf godot.tar.gz source/editor source/tests
        chmod 744 .github/docker/build.sh
    
    - name: Setup Docker Cache
      id: docker-cache
      uses: actions/cache@v3
      env:
        dockerfile: .github/docker/Dockerfile.${{matrix.name}}
      with:
        path: .docker-cache
        key: docker-${{matrix.name}}-${{hashFiles(env.dockerfile)}}
        restore-keys: docker-${{matrix.name}}-${{hashFiles(env.dockerfile)}}
    
    - name: Create Docker Container
      run: |
          if [ -e .docker-cache/snapshot.tar ]
          then
              docker load -i .docker-cache/snapshot.tar
          else
              docker build -t container -f ${{ github.workspace }}/.github/docker/Dockerfile.${{matrix.name}} .
              docker save container -o .docker-cache/snapshot.tar
          fi
    
    - name: Setup Build Cache
      uses: actions/cache@v3
      with:
        path: .scons-cache
        key: sconscache-${{matrix.name}}
        restore-keys: sconscache-${{matrix.name}}
    
    - name: Run Docker Image
      run: docker run -v "${{github.workspace}}./github/godot":"/godot/templates" container bla ${{env.SECRET_KEY}}
    
    - name: Cleanup
      run: |
        ls -la .templates
        ls -la /godot
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: templates
        path: templates/*
        retention-days: 3
