name: Test
on:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Download and extract Godot
            shell: bash
            run: |
                wget -q -O godot.tar.gz https://github.com/godotengine/godot/archive/refs/tags/4.0.1-stable.tar.gz
                tar xf godot.tar.gz --directory source/ --strip-components=1 --exclude=".*"
                rm -rf godot.tar.gz && rm -rf editor
                ls -la
                ls -la source
  
  
