name: 🛠️ Godot Build Service
on: 
  workflow_dispatch:

env:
  VERSION: "4.0.1"
  SECRET_KEY: ${{ secrets[format('{0}_KEY', github.event.inputs.profile)] }}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        name: ["windows", "linuxbsd", "web", "android"]
        arch: ["x86_64", "i686"]
        #name: ["web"]
        exclude:
          - name: web
            arch: "i686"
          - name: android
            arch: "i686"
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Prepare Enviroment
      run: |
        mkdir -p .godot .godot/source .godot/templates .godot/.scons-cache .godot/.docker-cache
        chmod 744 .github/docker/build.sh
        wget -q -O godot.tar.gz https://github.com/godotengine/godot/archive/refs/tags/${{env.VERSION}}-stable.tar.gz
        tar xf godot.tar.gz --directory .godot/source --strip-components=1 --exclude=".*"
        rm -rf godot.tar.gz .godot/source/editor .godot/source/tests
    
    - name: Setup Docker Cache
      id: docker-cache
      uses: actions/cache@v3
      with:
        path: .godot/.docker-cache
        key: docker-${{matrix.name}}
        restore-keys: docker-${{matrix.name}}
    
    - name: Create Docker Container
      run: |
          if [ -e .godot/.docker-cache/snapshot.tar ]
          then
              docker load -i .godot/.docker-cache/snapshot.tar
          else
              docker build -t container -f ${{github.workspace}}/.github/docker/Dockerfile.${{matrix.name}} .
              docker save container -o .godot/.docker-cache/snapshot.tar
          fi
    
    - name: Setup Build Cache
      uses: actions/cache@v3
      with:
        path: .godot/.scons-cache
        key: sconscache-${{matrix.name}}-${{matrix.arc}}}
        restore-keys: sconscache-${{matrix.name}}-${{matrix.arc}}}
    
    - name: Run Docker Image
      run: |
        docker run -v "${{github.workspace}}/.godot":"/godot" container ${{matrix.arch}} ${{env.SECRET_KEY}}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: templates
        path: .godot/templates/*
        retention-days: 3
